"use client";

import { useState } from "react";
import Image from "next/image";

/**
 * FeaturedProjectsCarousel component to cycle through robot projects.
 * @returns {JSX.Element} The rendered carousel.
 */
const featuredProjects = [
  {
    name: "Bubbles",
    type: "1lb Antweight Combat Robot",
    image: "/images/bubbles v1.jpg",
    title: "Offensive Strength & Versatility",
    description: "Bubbles is a custom-designed antweight featuring a lightweight carbon fiber chassis and a devastating vertical spinner, constantly evolving after each competition.",
    specs: [
      { label: "Chassis", value: "Lightweight, durable carbon fiber with TPU armor to absorb heavy impacts." },
      { label: "Drive", value: "Four-wheel drive for precision maneuverability and traction." },
      { label: "Weapon", value: "Powerful vertical spinner to deliver high-impact blows capable of shredding opponent armor." },
      { label: "Ongoing Innovation", value: "Our latest revision includes hub motors to maximize battery space and reduce friction." }
    ]
  },
  {
    name: "Horizon",
    type: "1lb Antweight Combat Robot",
    image: "/images/horizon v3.jpg",
    title: "High-Tip-Speed Destruction",
    description: "Horizon is a fierce horizontal spinner built to deliver massive kinetic energy hits, designed to outmaneuver and out-hit the competition.",
    specs: [
      { label: "Chassis", value: "Robust frame designed to withstand the immense forces generated by its weapon." },
      { label: "Weapon", value: "High-tip-speed horizontal spinner that dominates the arena with devastating blows." },
      { label: "Strategy", value: "Iterative design enhancements focus on maintaining weapon speed while ensuring structural integrity." },
      { label: "Focus", value: "Maximizing kinetic energy transfer to disable opponents quickly and efficiently." }
    ]
  }
];

export default function FeaturedProjectsCarousel(): React.ReactNode {
  const [currentIndex, setCurrentIndex] = useState(0);

  const nextSlide = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % featuredProjects.length);
  };

  const prevSlide = () => {
    setCurrentIndex((prevIndex) => (prevIndex - 1 + featuredProjects.length) % featuredProjects.length);
  };

  const project = featuredProjects[currentIndex];

  return (
    <div className="relative">
      <div className="premium-card p-8 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
        <div className="relative aspect-square rounded-2xl overflow-hidden shadow-2xl shadow-accent/20">
          <Image 
            src={project.image} 
            alt={project.name} 
            fill 
            className="object-cover transition-opacity duration-500" 
          />
        </div>
        <div>
          <div className="inline-block bg-accent/20 text-accent px-3 py-1 rounded-full text-sm font-bold mb-4">
            {project.type}
          </div>
          <h3 className="text-2xl font-bold mb-4">{project.title}</h3>
          <p className="text-gray-400 mb-6">{project.description}</p>
          <ul className="space-y-4 text-gray-300 min-h-[220px]">
            {project.specs.map((spec, index) => (
              <li key={index}><strong className="text-white block mb-1">{spec.label}:</strong> {spec.value}</li>
            ))}
          </ul>
        </div>
      </div>

      {/* Carousel Navigation */}
      <div className="flex justify-center mt-8 gap-4">
        <button 
          onClick={prevSlide}
          className="p-3 rounded-full bg-white/10 hover:bg-white/20 transition-colors border border-white/20"
          aria-label="Previous project"
        >
          <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
        </button>
        <div className="flex gap-2 items-center">
          {featuredProjects.map((_, index) => (
            <button
              key={index}
              onClick={() => setCurrentIndex(index)}
              className={`w-3 h-3 rounded-full transition-all ${index === currentIndex ? "bg-accent scale-125" : "bg-white/30 hover:bg-white/50"}`}
              aria-label={`Go to slide ${index + 1}`}
            />
          ))}
        </div>
        <button 
          onClick={nextSlide}
          className="p-3 rounded-full bg-white/10 hover:bg-white/20 transition-colors border border-white/20"
          aria-label="Next project"
        >
          <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
        </button>
      </div>
    </div>
  );
}
